import day_7
import gleeunit/should
import pprint

const test_input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

pub fn part_1_test() {
  day_7.do_part_1(test_input)
  |> should.equal(21)
}

pub fn part_2_test() {
  day_7.do_part_2(test_input)
  |> should.equal(40)
}

pub fn parse_test() {
  test_input
  |> day_7.parse_input
  |> pprint.debug
}
